server:
  port: 8080
spring:
  datasource:
    tasks:
      jdbcUrl: jdbc:postgresql://localhost:5432/eisetasks
      username: user
      password: password
      driver-class-name: org.postgresql.Driver